---
# tasks file for osconfig
- name: add sar cron jobs
  blockinfile:
    path: /var/spool/cron/root
    create: yes
    state: present
    block: |
      # Run system activity accounting tool every 10 minutes
      */10 * * * * /usr/lib64/sa/sa1 1 1
      # 0 * * * * /usr/lib64/sa/sa1 600 6 &
      # Generate a daily summary of process accounting at 23:53
      53 23 * * * /usr/lib64/sa/sa2 -A
      # run-parts
      08 * * * * run-parts /etc/cron.hourly
      02 4 * * * run-parts /etc/cron.daily
      22 4 * * 0 run-parts /etc/cron.weekly
      42 4 1 * * run-parts /etc/cron.monthly

- name: install ksh
  yum: name={{item}} state=latest
  with_items:
      - ksh
      - mlocate
      - nano

- name: install banner
  when: ansible_distribution == "Amazon"
  yum: name={{item}} state=latest
  with_items:
      - figlet

- name: install banner
  when: ansible_distribution == "CentOS"
  yum: name={{item}} state=latest
  with_items:
      - banner

- name: yum check-update
  shell: 'yum check-update || test $? -eq 100'

- name: yum clean all
  shell: 'yum clean all'

- name: append centos .bashrc
  when: ansible_distribution == "CentOS"
  blockinfile:
    path: /home/centos/.bashrc
    backup: yes
    state: present
    block: |
      # If not running interactively, do nothing
      case $- in
        *i* ) ;;
        *  ) return;;
      esac
      # User specific aliases and functions
      alias c=clear
      export PS1="\n\[$(tput sgr0)\]\[\033[38;5;2m\]\u\[$(tput sgr0)\]\[\033[38;5;15m\]@\h (\W) $ \[$(tput sgr0)\]"
      set -o vi

- name: append ec2-user .bashrc
  when: ansible_distribution == "Amazon"
  blockinfile:
    path: /home/ec2-user/.bashrc
    backup: yes
    state: present
    block: |
      # If not running interactively, do nothing
      case $- in
        *i* ) ;;
        *  ) return;;
      esac
      # User specific aliases and functions
      alias ls="command ls ${colorflag}"
      alias grep='grep --color=auto'
      alias fgrep='fgrep --color=auto'
      alias egrep='egrep --color=auto'
      alias c=clear
      export PS1="\n\[$(tput sgr0)\]\[\033[38;5;2m\]\u\[$(tput sgr0)\]\[\033[38;5;15m\]@\h (\W) $ \[$(tput sgr0)\]"
      set -o vi

- name: append root's .bashrc
  blockinfile:
    path: /root/.bashrc
    backup: yes
    state: present
    block: |
      # If not running interactively, do nothing
      case $- in
        *i*) ;;
        *) return;;
      esac
      # User specific aliases and functions
      alias ls="command ls ${colorflag}"
      alias grep='grep --color=auto'
      alias fgrep='fgrep --color=auto'
      alias egrep='egrep --color=auto'
      alias c=clear
      export PS1="\n\[$(tput sgr0)\]\[\033[38;5;1m\]\u\[$(tput sgr0)\]\[\033[38;5;15m\]@\h (\W) # \[$(tput sgr0)\]"
      set -o vi

# END
