---
# tasks file for httpd
- name: install the latest web components
  yum: pkg={{item}} state=latest
  with_items:
    - httpd
    - git
    - epel-release
    - python-pip
    - python-virtualenv
    - python-httplib2

- name: update all installed packages
  yum:
    name: "*"
    state: latest

- name: Clone git repo containing website
  git:
    repo: https://github.com/dwasmer/myweb.git
    dest: /var/www/html
    version: develop

- name: start httpd at boot
  service:
    name: httpd
    enabled: yes
    state: started

# END
